services:
  - type: web
    name: yt-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    region: oregon
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: yt-mongo
    plan: starter
    databaseName: yt
    ipAllowList: []